### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by albaer** [wtag/dragonfly-google_data_store#5]
Hi @luxflux,

Thanks for all of your work on this. I am wondering if you and/or wtag are still maintaining this gem. I used this as the base of our dragonfly/GCS integration, and wanted to make that work more reusable. I'm happy do PRs into here if you'd like, or I can go ahead and make a separate gem. The main changes I needed to make were:

- Addressing missing filename/extension (similar to #2)
- Allowing for use of `credentials` instead of `keyfile` so you can pass in a hash, as allowed by updates to the google storage gem
- Adding some tests

**Comment by luxflux** [comment]
Thanks for reaching out, @albaer. I missed the notifications on this repo, but we're definitively open to adding more functionality.

**Comment by albaer** [comment]
Great! I don't think it will be in the next month, I'll make some PRs here when I get back around to this. Thanks!
